spring.application.name=pricebot
telegram.bot.token=${BOT_TOKEN}

spring.datasource.url=jdbc:sqlite:pricebot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.username=kirekq
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.main.web-application-type=none